### ISSUE TITLE
Kurzreview

### ISSUE THREAD

**Issue by signalwerk** [marc-hatt/portfolio#2]
## Hallo Marc
Ich habe mir kurz dein Portfolio durchgeschaut. Ich habe nur kurz drauf geschaut, da ich davon ausgehe, dass du noch nicht fertig bist. Hier vielleicht ein paar Inputs (eher technisch):

* home auf portfolio-seite noch nicht verlinkt
* ich würde in der Benotung nur die «Portfolio»-Seite beurteilen, da die andere einerseits nicht aufgabe wäre, andererseits ja noch funktional nicht fertig ist. ok? 
* Wenn du willst, kannst ja bei Pascale die Videos von Vimeo klauen schau mal [hier](https://github.com/pascaleva/portfolio/blob/gh-pages/index.html#L233)
* gibt es noch mehr Bilder aus dem Prozess?

Wenn du einen  Kommentar oder ein Problem hast, bitte hier antworten.

**Comment by marc-hatt** [comment]
## Sali Stefan, vielen Dank für deine Inputs!

Ich habe die letzten Tage/Wochen damit verbracht den Text und auch die Technik des Portfolios zu verfeinern und auch einige gestalterische Anpassungen vorgenommen. Da ich deine Kurzreview nicht unbeantwortet lassen wollte, anbei Kommentare zu deinem Feedback:

* home auf portfolio-seite noch nicht verlinkt
_Wurde nun gemacht. Die Links verweisen nun auf die «Home»-Page. Das mit dem z-index hat erstaunlich gut funktioniert, auch wenn ich, hätte ich mehr Zeit für Recherche, einen Transition-Effekt vorgezogen hätte. Für die Einfachheit der Lösung funktioniert sie aber erstaunlich gut._

* ich würde in der Benotung nur die «Portfolio»-Seite beurteilen, da die andere einerseits nicht aufgabe wäre, andererseits ja noch funktional nicht fertig ist. ok?
_Du hast Recht, die Homepage ist aus Eigeninteresse entstanden, da ich mein Wissen, was Bootstrap angeht, vertiefen wollte. Die Seite «Portfolio» ist ja relativ unspektakulär und auf gute Lesbarkeit ausgelegt. Solltest du dich aber dafür entscheiden zumindest den Mehraufwand anzuerkennen, wär ich dir natürlich auch nicht böse. ;)_

* Wenn du willst, kannst ja bei Pascale die Videos von Vimeo klauen schau mal hier…
_Vielen Dank, hab' ich gemacht… auch wenn ich Anfangs Probleme mit dem iframe hatte. Nun sieht die Seite auch auf Mobile top aus._

* gibt es noch mehr Bilder aus dem Prozess?
_Die gibt es, allerdings konnte ich mich noch nicht entscheiden ob ich sie denn einfügen sollte._

Ich hoffe du bist sicher ins neue Jahr gerutscht, ich wünsche dir einen guten Start!

**Comment by signalwerk** [comment]
@marc-hatt Super. Merci für die Rückmeldung. Das klingt doch schon mal ganz vielversprechend. Ich freue mich auf Eure Arbeiten!

**Comment by marc-hatt** [comment]
Nochmals als kleines Feedback:
Technik/Design ist wohl zu 99% fertig (Feinschliff an ein paar Ecken und Kanten ist noch zu machen).
Überarbeitung hat wohl nur noch der Text nötig. harttaberflair.tk falls du dir das Ganze online anschauen möchtest.

Warum ich dir eigentlich schreibe. Eine kleine Frage:
Wird das CSS in irgendeiner Form bewertet? Wie zum Beispiel Stil-Hierarchie und Sauberkeit? Denn falls ja muss ich da noch bis zum Abschluss des Projekt ordentlich aufräumen.

**Comment by signalwerk** [comment]
@marc-hatt sorry ich hatte deine frage gar nicht beantwortet. nein CSS und Code werden nicht bewertet. jeder studierende steht an einem anderen punkt. deshalb lege ich mehr wert auf die auseinandersetzung mit dem inhalt.
